version: '3'

services:
  database:
    image: postgres:14.5
    restart: on-failure
    volumes:
      - gallery_db:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_PORT: ${DB_PORT}
  
  app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8888:8000"
    depends_on:
      - database
    command: sh run.sh
    volumes:
      - .:/app

volumes:
  gallery_db: