# Generated by Django 4.1.2 on 2022-11-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('album_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='photo.album')),
                ('content', models.ImageField(default=None, upload_to='static/images')),
                ('album', models.ManyToManyField(related_name='image_set', to='photo.album')),
            ],
            bases=('photo.album',),
        ),
    ]
