# Generated by Django 4.1.3 on 2022-11-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_imagegallery_remove_image_category_delete_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_album', models.CharField(choices=[('Album1', 'Album1'), ('Album2', 'Album2'), ('Album3', 'Album3'), ('Album4', 'Album4')], default='1', max_length=20)),
                ('image_content', models.ImageField(default=None, upload_to='static/images')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
