# Generated by Django 4.1.2 on 2022-11-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_image_delete_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_album',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_content',
        ),
        migrations.AddField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ManyToManyField(to='photo.album'),
        ),
    ]
