# Generated by Django 4.1.2 on 2022-11-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_album_remove_image_image_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_content',
            field=models.ImageField(default=None, upload_to='static/images'),
        ),
    ]
